---
- name: Copy file to remote server and delete it locally
  hosts: main
  become: true
  tasks:
    - name: Copy file to remote server
      ansible.builtin.copy:
        src: ./testfile
        dest: /home/ubuntu/testfile

    - name: Drop file on the local server
      delegate_to: localhost
      ansible.builtin.file:
        path: ./testfile
        state: absent
