
apiVersion: v1
kind: Service
metadata:
  name: java-web-server-service
spec:
  selector:
    app: java-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
