# tomcat.yml
---
- name: Converge
  hosts: all
  become: true
  gather_facts: true


  tasks:
    - name: Include the Tomcat role from vars.yml
      include_vars:
        file: vars.yml

    - include_role:
        name: "{{ tomcat_role }}"
      vars:
        uid: 1234
        gid: 1234
        install_java: false
        tomcat_version: 10.0.27
        tomcat_home: /opt/apache-tomcat
        java_options: -Djava.net.preferIPv4Stack=false
        catalina_options: -Xms1G -Xmx8G
